if (CPACK_GENERATOR MATCHES "DEB")
    set(CPACK_SET_DESTDIR true)
    set(CPACK_PACKAGING_INSTALL_PREFIX "/tmp")
    set(CMAKE_INSTALL_PREFIX "/opt/${CPACK_PACKAGE_NAME}-${CPACK_PACKAGE_VERSION_MAJOR}.${CPACK_PACKAGE_VERSION_MINOR}.${CPACK_PACKAGE_VERSION_PATCH}")
    set(CPACK_DEBIAN_PACKAGE_PRIORITY "optional")
    set(CPACK_DEBIAN_PACKAGE_SECTION "misc")
    set(CPACK_DEBIAN_ARCHITECTURE ${CMAKE_SYSTEM_PROCESSOR})
    # autogenerate dependency information
    set (CPACK_DEBIAN_PACKAGE_SHLIBDEPS ON)
elseif(CPACK_GENERATOR MATCHES "TGZ")
    set(CPACK_PACKAGING_INSTALL_PREFIX "")
endif()

message("CMAKE_PROJECT_NAME:         " ${CMAKE_PROJECT_NAME})
message("CPACK_INSTALL_PREFIX:       " ${CPACK_INSTALL_PREFIX})

